services:
  - type: web
    name: quan-ly-hoc-sinh-vi-pham
    env: node
    buildCommand: npm install
    startCommand: node server-mongodb.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
